name: MechWiz_CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  AWS_REGION: "us-east-1"

jobs:
  deploy-to-ebs:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS Elastic Beanstalk CLI
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip
          pip3 install awsebcli --upgrade

      - name: Package Application for EBS
        run: |
          zip -r app.zip * .[^.]* -x "**node_modules**" "**.git**" "**.github**"
      
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "MechWiz" \
            --version-label "deploy-${{ github.run_number }}" \
            --source-bundle S3Bucket="elasticbeanstalk-${{ env.AWS_REGION }}-$(aws sts get-caller-identity --query Account --output text)",S3Key="app-${{ github.run_number }}.zip"

          aws elasticbeanstalk update-environment \
            --environment-name "MechWiz-env" \
            --version-label "deploy-${{ github.run_number }}"
