name: Smart Warranty CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  GIT_URL: "https://github.com/MageshwaranKCloudEngineer/Smart_warranty_project"
  DOCKER_IMAGE: "magesh506/smart_warrenty_calculator"
  IMAGE_TAG: "latest"
  AWS_REGION: "us-east-1"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $DOCKER_IMAGE:$IMAGE_TAG .
          docker push $DOCKER_IMAGE:$IMAGE_TAG

      - name: Deploy Docker Compose on EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Checking if Docker Compose is installed..."
            if ! command -v docker-compose &> /dev/null
            then
              echo "Installing Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            echo "Navigating to deployment directory..."
            cd ~/Smart_warranty_project || mkdir -p ~/Smart_warranty_project && cd ~/Smart_warranty_project
            
            echo "Stopping existing containers..."
            docker-compose down || true

            echo "Pulling latest changes..."
            git pull origin master

            echo "Pulling the latest Docker image..."
            docker pull $DOCKER_IMAGE:$IMAGE_TAG

            echo "Starting services using Docker Compose..."
            docker-compose up -d --build --scale app=3

            echo "Listing running containers..."
            docker ps -a
          EOF

      - name: Debug Docker Containers on EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Checking running Docker containers..."
            docker ps -a
            echo "Fetching logs from smart-warranty-calculator..."
            docker logs smart-warranty-calculator || echo "No logs found for smart-warranty-calculator"
          EOF

      - name: Logout from Docker Hub
        if: always()
        run: docker logout

      - name: Success Message
        if: success()
        run: echo "Pipeline completed successfully with Docker Compose!"

      - name: Failure Message
        if: failure()
        run: echo "Pipeline failed."
